### ISSUE TITLE
How to remove the heart/spade/clover (♥ ♠ ♣) symbols from theorems?

### ISSUE THREAD

**Issue by moshpirit** [ElegantLaTeX/ElegantBook#181]

**Comment by EthanDeng** [comment]
you need remove these symbols code from elegantbook.cls, which you can find them in the tcb math environment settings, for the latest version, please refer to the [code](https://github.com/ElegantLaTeX/ElegantBook/blob/34e22250193309fea9ef039104be2557ac5cfbd5/elegantbook.cls#L854-L877)

**Comment by moshpirit** [comment]
This is exactly what I needed, thank you :blush:, BTW, how could I change them for a little SVG image? (ie: instead of viewing a :heart:, viewing let's say Overleaf's logo).

**Comment by EthanDeng** [comment]
You can search online for the question: `include svg image latex`.

**Comment by moshpirit** [comment]
Sorry if I didn't explain myself correctly, I know how to embed SVG files with `\includegraphics`, but I'm not sure if this could be done in this specific LaTeX template (I'm kind of noob with it) and what line should I change. Would it be possible to just exchange `$heartsuit$` by that or do I need to do something else? Thank you so much for replying!

**Comment by EthanDeng** [comment]
If I understand correctly, you can try two things:
1. convert svg to tikz code (for example [svg2tikz](https://github.com/xyz2tex/svg2tikz)), then define the tikz code as a user command `\newcommand{\usrcmd}{tikz code}`, then include `\usrcmd` in your file.
2. `specific LaTeX template` means latex pkg? you can browser the [CTAN](https://ctan.org/) center for related pkgs which may solve your problem.

I am not familiar with svg image, and little experience with that format except *converting svg img to base64 code in order to embed it in html/css*, so you may find the correct answers by yourself.

**Comment by moshpirit** [comment]
Awesome, thank you :)
