### ISSUE TITLE
version 3.09 corrupts templates / mess up with font maps?

### ISSUE THREAD

**Issue by tfran1971** [ElegantLaTeX/ElegantBook#48]
When I compile my book project, I get the following error (several times): "Font U/esint/m/n/10=esint10 at 10.0pt not loadable: Metric (TFM) file not found. \maketitle". I saw in the class file that a package named mtpro2 is requested, which does not exist on CTAN. I don't know this has to do with the issue....
Anyway, I don't know from where the error comes. Everything worked fine until Version 3.08.
I'm using up to date MiKTeX 2.9 under Windows 10.

**Comment by tfran1971** [comment]
If I comment out the 'esint' package then it works. I don't know whether this was intended  feature. Even if MiKTeX load all missing packages on the fly, 'esint' just does not work. I suppose it works fine on linux systems/TeXlive. Please consider to remove these interoparable barriers in fonts (if applicable).

**Comment by muzimuzhi** [comment]
`mtpro2` package is required only when class option `mupro2` is used. And `mtpro2.sty` is provided as a file of [CTAN package `mtpro2lite`](https://ctan.org/pkg/mtp2lite). This package is neither included by texlive nor miktex, but can be downloaded from CTAN.

Can you provide a minimal but complete example that reproduces the problem? See [this Q&A on meta-TeX-SX](https://tex.meta.stackexchange.com/q/228/79060) for what that is.

**Comment by EthanDeng** [comment]
Did you use the `mtpro2` option? **If you didn't install this fonts manually, please do not use this option.** 

Moreover, this version has been upload to Overleaf, please refer [ElegantBook](https://www.overleaf.com/latex/templates/elegantbook-template/zpsrbmdsxrgy), there is no warnings or errors if you don't choose the `mtpro2` option, you can provide more information.

**Comment by tfran1971** [comment]
Hello. No, I don’t use this option. I think my issue comes from \RequirePackage{esint} in the *.cls file. Even if I installed this package under MiKTeX it does not work. I have to comment out this \RequirePackage{esint} and then my source files get compiled. BTW: That’s why even the simple minimal working example shown on the last page of the user guide did not compile with my MiKTeX installation.
What I wanted from you is to check whether ‘esint’ is really needed and if yes, whether there is a way to ensure that it runs both with TL as well as MiKTeX.
Thanks

Von: Dongsheng Deng
Gesendet: 25 August 2019 03:22
An: ElegantLaTeX/ElegantBook
Cc: tfran1971; Author
Betreff: Re: [ElegantLaTeX/ElegantBook] version 3.09 corrupts templates / messup with font maps? (#48)

Did you use the mtpro2 option? If you didn't install this fonts manually, please do not use this option.
Moreover, this version has been upload to Overleaf, please refer ElegantBook, there is no warnings or errors if you don't choose the mtpro2 option, you can provide more information.

**Comment by muzimuzhi** [comment]
I cannot reproduce your problem. Hence an mwe (see https://github.com/ElegantLaTeX/ElegantBook/issues/48#issuecomment-524490333), as well as your local version info of every loaded package in your mwe, is necessary.

**Comment by ustcfdm** [comment]
Actually I have the same problem. I can reproduce this problem. A minimal example is shown below.

`\documentclass[11pt]{elegantbook}

\title{An Elegant LaTeX Template for Books}
\subtitle{Classic ElegantLaTeX Template}

\author{Ethan Deng and Liam Huang}
\institute{ElegantLaTeX Program}
\date{2019}
\version{3.09}

\extrainfo{Victory will not come to us unless we go to it. }

\logo{logo.png}
\cover{cover.jpg}

\begin{document}

\maketitle

Whatever.

\end{document}`

It seems that the problem is from `\maketitle`. If I comment this line, there won't be any issue. I am using 
- Windows 10 64 bit
-  MikTex 2.9
- VS code + LaTex Workshop

**Comment by EthanDeng** [comment]
根据排查，以及群里用户的反馈，这个问题产生的原因是 `esint` 包，而不是 ElegantBook 导致的。下面这个你们在运行的时候应该就会报错。

According to the feedback from users in the user group, the problem was caused by the 'esint' package, not the ElegantBook. You will encounter with errors when you run it.

```tex
\documentclass{article}

\usepackage{amsmath}
\usepackage{esint}

\begin{document}
$a_n$

% \begin{equation}
% \oiint_{a}^{b} f(x) \, dx
% \end{equation}

\end{document}
```

**Comment by muzimuzhi** [comment]
1. The problem is caused by missing `esint10.tfm` file in `esint` version 1.2c.
1. Down-grading to v1.2b by execute `tlmgr restore esint 51679` from command line, or downloading the missing `esint10.tfm` file from [this link on svn repo of texlive](https://tug.org/svn/texlive/trunk/Master/texmf-dist/fonts/tfm/public/esint/esint10.tfm%3Frevision%3D90%26view%3Dco%26pathrev%3D51934) and then move it to directory `` `kpsewhich --var-value TEXMFDIST`/fonts/tfm/public/esint`` can both fix the problem
1. For more detailed steps and explanations, see this article in Chinese: [_缺 TFM 文件：字体包 esint 需从 v1.2c 降级到 v1.2b_](https://zhuanlan.zhihu.com/p/79916238) on zhihu (知乎).

**Comment by tfran1971** [comment]
Thanks. What if I’m using MiKTeX? How to fix the problem there?

Von: muzimuzhi
Gesendet: 27 August 2019 03:33
An: ElegantLaTeX/ElegantBook
Cc: tfran1971; Author
Betreff: Re: [ElegantLaTeX/ElegantBook] version 3.09 corrupts templates / messup with font maps? (#48)

1. The problem is caused by missing esint10.tfm file in esint version 1.2c.
2. Down-grading to v1.2b by execute tlmgr restore esint 51679 from command line, or downloading the missing esint10.tfm file from this link on svn repo of texlive and then move it to directory `kpsewhich --var-value TEXMFDIST`/fonts/tfm/public/esint can both fix the problem
3. For more detailed steps and explanations, see this article in Chinese: 缺 TFM 文件：字体包 esint 需从 v1.2c 降级到 v1.2b on zhihu (知乎).

**Comment by muzimuzhi** [comment]
1. texlive has updated esint v1.2c (without version stepped) and fixes the missing-tfm problem.
1. I don't use miktex. But as long as using texmf tree, putting the tfm file under some sub-directory and then refreshing tex database should still make sense for miktex. see https://miktex.org/Package/Browse/esint

**Comment by ustcfdm** [comment]
@tfran1971 In MikTex, the esint package has been updated to 1.2d, which has fixed this problem.

**Comment by muzimuzhi** [comment]
I think it's time to cloes this esint-only issue.
